version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build: ./src/
    ports:
      - "4002:4002"
    tty: true
    links:
      - db
    volumes:
      - ./src:/usr/src/app/src
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
